### PR TITLE
solve issues: #1 #4 and #5

### PR DESCRIPTION
**Pull request by srozb**
Actually solves:
* https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/1 - No udp timeout set here. HVAC doesn't respond to datagram encrypted with the default encryption key. Need to provide the correct encryption key to make it communicate. This is an adhoc fix - not the best one.

* https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/5 - home assistant >= 0.84 fix import.

### CODE REVIEW

**Comment by srozb** [comment]
> Unfortunately it is freezing even with this fix

Are you using the correct encryption key for communicating with the hvac? 
https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/blob/bc86a879f3f6d2be5afcab8441995217777feeb2/README.md (paragraph 4)

**Comment by RobHofmann** [comment]
Hi! sorry for the late reply.  What does the uid do? also, could you update the PR for the latest version?

Latest version in master should work with HASSIO 0.90.2

**Comment by srozb** [comment]
This PR works fine with home-assistant (venv) 0.90. AFAIR `UID` parameter is some kind of device identifier required by my device to respond to the commands. I think you should test it on your device to be sure it stays compatible with other gree HVACs. Mine is branded as "Innova".

**Comment by RobHofmann** [comment]
Partially merged in https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/commit/ab4939b2b7412afca3e46d9921a94f869415736c.

This version should also work for you @srozb :).

Let me know if any issues arise.

**Pull request closed without merging**
