### PR TITLE
v2.14

### PR DESCRIPTION
**Pull request by toughvj**
- Added support for built-in temp sensor
- Added suport for built-in light sensor
- Extended auto_light functionality to be usable with light sensor

IMPORTANT!
From this version, auto_light and auto_xfan must be set as input_boolean

### CODE REVIEW

**Review by jodewee — COMMENTED** [review]
Tested with bulex vivair.
encryption v2
no autolight or autoxfan function
all works fine! (HA 2024.07)

**Comment by Machaeon** [comment]
The horizontal swing setting seems to have disappeared from the interface.

**Comment by toughvj** [comment]
no. it's not

**Comment by stenvix** [comment]
image
image
This may be related to your code, but in 2.13 it disappeared as well

**Comment by toughvj** [comment]
have you set horizontal_swing: true ifconfig?

**Comment by Machaeon** [comment]
No, I haven't set it.

**Comment by toughvj** [comment]
So? Everything is in readme file

**Comment by Machaeon** [comment]
`horizontal_swing: <OPTIONAL: boolean (true/false); this feature will enable horizontal swing on devices that have this functionality. This feature replaces presets in the UI`
UI allows to set the swing range. I do not want to replace UI Presets so I didn't set this option.

**Comment by toughvj** [comment]
I'm a little confused. You write that horizontal_swing doesn't work, but you don't actually use it. Do you mean that you are using the built-in presets and want them to appear in the selection list if you don't want to use horizontal_swing? Do you mean something else?

**Comment by Machaeon** [comment]
Well, yes, adding the horizontal_swing option to the config enables the horizontal swing settings in the UI card. I was confused by the words "This feature replaces presets in the UI" and didn't add it before. Is it just me, or did previous versions have a swing setting in the UI without adding this option?

**Comment by toughvj** [comment]
You're right, previous versions didn't require this option. I have now made one more change: if the horizontal_swing option is not set, the device in HA does not have a preset option, so it does not appear as an empty list in the UI.

**Review by RobHofmann — APPROVED** [review]

**Comment by RobHofmann** [comment]
Tested! Works like a charm again. Thanks @toughvj :).

**Pull request merged**
