### PR TITLE
Added support for lights, xfan, sleep and powersave mode.

### PR DESCRIPTION
**Pull request by wjketting**
Big thanks for creating this curstom addon.
I like this one above the mqtt version but was missing some of the options that where available in the mqtt version (mqtt template switch).

I updated the code and tested it. Think it's ready to share.
Can you review/test it and let me know what you think?
Hope you find this an usefull addition as well.

Thanks in advance and regards.

### CODE REVIEW

**Comment by wjketting** [comment]
Example how I have this implementen in my UI:
afbeelding

**Comment by RobHofmann** [comment]
Hi I just checked this. The lights part seems to work for me.

Can you elaborate on what xfan, Sleep and Powersave do? They do not work for my model.

PR seems fine. Thanks for your efforts and PR!

**Comment by wjketting** [comment]
xfan can be used in cool and dry mode.
when xfan is turned on the airco fan will run for a while when cooling is switched off to allow the unit to "dry" before it switches off and closed to avoid unpleasent smell.
powersave can only be used in cook mode.
Gree documentation is not very informing what it accualy does but it seems the inside temperature will vary a bit depending on the outside temperature. I'll try to find more info on this one.
sleep mode is a special mode for sleeping. temperature will be lower when unit is switched on and than increasing a bit over time (when you - hopefully - are in deeper sleep). My unit has severall sleep modes. Not sure yet how to set the different modes (SwhSlp only seems to be either 0 or 1).
Hope this helps.

**Comment by RobHofmann** [comment]
Hi! Thanks for clarifying. I'm going to try this. But for now everything works and so the PR can be merged.

Thanks again for your effort!

Cheers!

**Pull request merged**
