### PR TITLE
Trying to read AC internal temperature sensor if no external sensor is specified. Include an -40 offset if necessary.

### PR DESCRIPTION
**Pull request by Machaeon**

### CODE REVIEW

**Comment by RobHofmann** [comment]
For me it seems to display a temperature, however it differs from the temp sensors i have in those rooms. theres a range of about 3 degrees difference between those sensors. Im not sure if the sensors are just bad or if something is not working properly.

I hope other people can confirm this PR (maybe @toughvj can check this :)).

PS. Can you update the code to the latest version currently in main? It currently has some conflicts :).

**Comment by edisonbar** [comment]
Its working on my Gree Clivia .Temperature readings are Ok.

**Comment by toughvj** [comment]
this will work, but only on devices that have a built-in temperature sensor. If a device does not have such a sensor, the component will throw an error and will not even start. This change is on my to-do list but I still have mixed feelings about it. In most cases, the temperature is read from the remote control, so it does not always show the actual temperature in the room.
For now, I propose to hold off on this PR. Next week I will publish a change that will probably include this functionality and will not cause a crash on units without a temperature sensor.

**Comment by Machaeon** [comment]
@toughvj, could you please describe which line of code will generate the error if the AC does not have an internal sensor?

**Comment by toughvj** [comment]
If unit does not have temperature sensor, reading TemSen will return no value and GreeGetValues() will throw index out range error.

**Comment by janmashat** [comment]
Works like a charm! (any way to get back the on/off controls without going through the 3 dots?)

Screenshot 2024-06-19 at 16 23 27

**Comment by Machaeon** [comment]
> If unit does not have temperature sensor, reading TemSen will return no value and GreeGetValues() will throw index out range error.

@toughvj, I can fix it. Do it or wait for your PR?

>any way to get back the on/off controls without going through the 3 dots?

@janmashat, I'm not quite sure what you mean by that. can you explain more?

**Comment by toughvj** [comment]
@Machaeon please  wait for my PR since I want to rebuild SyncState() to allow any further changes with new functionality.

@janmashat U should edit climate card properties and add HVAC model function from gui.

**Comment by jan--m** [comment]
Yep, adding the following to my `ui-lovelace.yaml` did the trick, thanks!
```
        features:
          - type: climate-hvac-modes
            hvac_modes:
              - heat
              - cool
              - dry
              - fan_only
              - 'off'
```
Screenshot 2024-06-20 at 10 43 23

**Comment by janmashat** [comment]
Yep, adding the following to my `ui-lovelace.yaml` did the trick, thanks!
```
        features:
          - type: climate-hvac-modes
            hvac_modes:
              - heat
              - cool
              - dry
              - fan_only
              - 'off'
```
Screenshot 2024-06-20 at 10 43 23

**Comment by RobHofmann** [comment]
@toughvj can you find something of this PR? :)

**Comment by toughvj** [comment]
@RobHofmann sure thing but do you mean the temperature reading or the one @janmashat  mentioned?

**Comment by RobHofmann** [comment]
> @RobHofmann sure thing but do you mean the temperature reading or the one @janmashat mentioned?

The original PR :). It would be nice to add this feature.

**Comment by toughvj** [comment]
@RobHofmann. please try attached file. Component gets current temperature from built-in sensor only when external temp_sensor entity id is NOT set in config.yaml
It also contain support for light sensor (various devices).
Please let me know if it is ok
[climate.txt](https://github.com/user-attachments/files/15961777/climate.txt)

**Comment by RobHofmann** [comment]
Works like a charm. Can you turn that last version into a PR?

**Comment by toughvj** [comment]
good news ;) I'm still waiting for @red to test the light sensor feature, if everything is OK, I'll do PR.

**Comment by toughvj** [comment]
@RobHofmann this can be rejected because of #188

**Pull request closed without merging**
