### PR TITLE
Some fixes for None types, cleanup and extra checks

### PR DESCRIPTION
**Pull request by RobHofmann**
This might break some features, but it restores the main feature: being able to control your AC.

@toughvj please take a look at this. My AC's are no longer unavailable anymore. However the light/autolight features seem to have stopped working.

### CODE REVIEW

**Comment by RobHofmann** [comment]
Everything is working again. Extra checks added. Let me know if anything arrises.

**Comment by toughvj** [comment]
hi @RobHofmann, I'm sorry for the lack of response. I rewrote some of the integration, removed the need to use helpers, and replaced everything with service calls. Integration is now independent of the state machine.
All service calls have 3 acceptable parameters: on, off, toggle.

Below is the list of service calls:

set_light
set_xfan
set_health
'set_powersave
set_sleep
set_eightdegheat
set_air
set_autolight
set_autoxfan
set_light_sensor
set_anti_direct_blow
temp_increment
temp_decrement

Once a device is added to HA, it receives new attributes corresponding to the state after each service call.

Screenshot 2024-07-25 at 02 18 02 PM


Please let me know what you think
[climate.txt](https://github.com/user-attachments/files/16377458/climate.txt)

**Comment by RobHofmann** [comment]
i've tried it. the components stay unavailable after boot with these errors:
```yaml
2024-07-27 13:45:48.238 ERROR (MainThread) [homeassistant.config] Invalid config for 'climate' from integration 'gree' at climate.yaml, line 10: 'health' is an invalid option for 'gree.climate', check: health, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 11: 'sleep' is an invalid option for 'gree.climate', check: sleep, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 12: 'powersave' is an invalid option for 'gree.climate', check: powersave, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 13: 'auto_xfan' is an invalid option for 'gree.climate', check: auto_xfan, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 14: 'auto_light' is an invalid option for 'gree.climate', check: auto_light, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 8: 'lights' is an invalid option for 'gree.climate', check: lights, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 9: 'xfan' is an invalid option for 'gree.climate', check: xfan, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
2024-07-27 13:45:48.238 ERROR (MainThread) [homeassistant.config] Invalid config for 'climate' from integration 'gree' at climate.yaml, line 25: 'lights' is an invalid option for 'gree.climate', check: lights, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 26: 'xfan' is an invalid option for 'gree.climate', check: xfan, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 27: 'health' is an invalid option for 'gree.climate', check: health, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 28: 'sleep' is an invalid option for 'gree.climate', check: sleep, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 29: 'powersave' is an invalid option for 'gree.climate', check: powersave, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 30: 'auto_xfan' is an invalid option for 'gree.climate', check: auto_xfan, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
2024-07-27 13:45:48.238 ERROR (MainThread) [homeassistant.config] Invalid config for 'climate' from integration 'gree' at climate.yaml, line 41: 'lights' is an invalid option for 'gree.climate', check: lights, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 42: 'xfan' is an invalid option for 'gree.climate', check: xfan, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 43: 'health' is an invalid option for 'gree.climate', check: health, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 44: 'sleep' is an invalid option for 'gree.climate', check: sleep, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 45: 'powersave' is an invalid option for 'gree.climate', check: powersave, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
Invalid config for 'climate' from integration 'gree' at climate.yaml, line 46: 'auto_xfan' is an invalid option for 'gree.climate', check: auto_xfan, please check the docs at https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent
```

**Comment by toughvj** [comment]
And everything is ok. There is no need to use helpers. Everything is built-in in component. Every changes are made by calling service e.g.

climate.set_autoxfan
entity_id: climate.some_ac
data:
  mode: toggle

**Comment by RobHofmann** [comment]
Wait I think I dont understand you. Should I modify my config now?

Should I remove all the input_booleans?

**Comment by toughvj** [comment]
yes, in this version there is no need to use input booleans and they should be removed from the configuration as they will signal a configuration error. All control is done by service calls.

**Comment by RobHofmann** [comment]
Alright. i've removed them. Im now getting None fails again:

```
2024-07-31 12:46:43.116 ERROR (MainThread) [homeassistant.components.climate] Error adding entity climate.zolderkamer_ac for domain climate with platform gree
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1361, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/gree/climate.py", line 977, in async_added_to_hass
    self._attributes['auto_light'] = state.attributes['auto_light']
                                     ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'
2024-07-31 12:46:43.121 ERROR (MainThread) [homeassistant.components.climate] Error adding entity climate.slaapkamer_ac for domain climate with platform gree
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1361, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/gree/climate.py", line 977, in async_added_to_hass
    self._attributes['auto_light'] = state.attributes['auto_light']
                                     ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'
2024-07-31 12:46:43.124 ERROR (MainThread) [homeassistant.components.climate] Error adding entity climate.slaapkamer_puck_ac for domain climate with platform gree
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1361, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/gree/climate.py", line 977, in async_added_to_hass
    self._attributes['auto_light'] = state.attributes['auto_light']
                                     ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'
```

Did you apply your changes on my latest version? These errors seem to have returned from an older version.

**Pull request merged**
